### ISSUE TITLE
Headline types

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-vertnet-plus#6]
https://github.com/gbif/hp-vertnet-plus/blob/master/resources/norms.md

I notice that you are using `h1` for the top level headlines. Since `h1` is taken by the title of the page, then I suggest you jump straight to `h2` instead (and similar transform h2 to h3). I believe that would produce a better result, both visually and semantically.

**Comment by dbloom** [comment]
That was good advice, and I made the adjustment. I also removed the lowest level of the hierachy (Examples) and replaced them with bold text instead. Makes the toc much cleaner.
