### ISSUE TITLE
Code blocks text wrapping

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-vertnet-plus#7]
On the old VertNet site your codeblocks wrapped text. That isn't the case in this theme.
If you want text to be wrapped inside a codeblock you need to add explicit css to do so. 

CSS is added in https://github.com/gbif/hp-vertnet-plus/blob/master/_sass/_main.scss
e.g.
```
code {
  white-space: normal;
}
```

**Comment by dbloom** [comment]
Understood. Added to my list of resources.
