### ISSUE TITLE
Blurry pictures

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-vertnet-plus#8]
Regarding https://hp-vertnet-plus.gbif-staging.org/resources/norms
It is a pretty frog, but surely there must be pictures available that aren't that blurry! It looks like a screenshot from a VHS.

How about this one for example. It even sits on a VertNet green moss.
https://inaturalist-open-data.s3.amazonaws.com/photos/62616806/original.jpeg
from 
https://www.gbif.org/occurrence/2576292091

*before*
<img width="651" alt="Screenshot 2022-05-04 at 09 31 17" src="https://user-images.githubusercontent.com/6759267/166639083-d024f323-8ffe-4be7-ac88-963166d0d34e.png">
*after*
<img width="652" alt="Screenshot 2022-05-04 at 09 31 51" src="https://user-images.githubusercontent.com/6759267/166639094-1c6f8ea0-54c8-46f7-b1a6-c20214e30840.png">

**Comment by dbloom** [comment]
Thanks @MortenHofft The image was a test and I got distracted with the text blocking issue. Now that both are resolved, I have used your suggested image since it was better than the first attempt and it gives me the chance to use my planned image on another page.
